TwoRavens/TwoRavens

assets/app/app.js
rook/rookpreprocess.R
tworaven_apps/rook_services/views.py
tworaven_apps/workspaces/workspace_util.py

- use d3m config values to call preprocess
- receive/handle JSON in request body instead of POST with solaJSON key
- for the D3M domain, don't try to load the zelig5 model files

fix to get preprocess working

---

tworaven_apps/rook_services/views.py

e.g. Differentiate between string and dict when trying to insert session id

attempt fix for view_rook_route

---

tworaven_apps/api_docs/templates/swagger/v1_defn_basic.yaml
tworaven_apps/api_docs/templates/swagger/v1_paths_ta2.yaml
tworaven_apps/api_docs/views.py
tworaven_apps/api_docs/views_swagger.py
tworaven_apps/ta2_interfaces/grpc_util.py
tworaven_apps/ta2_interfaces/req_start_session.py
tworaven_apps/ta2_interfaces/templates/grpc/ta3ta2_api_form.html
tworaven_apps/ta2_interfaces/templates/test_responses/startsession_ok.json
tworaven_apps/ta2_interfaces/testing/__init__.py
tworaven_apps/ta2_interfaces/testing/test_grpc_util.py
tworaven_apps/ta2_interfaces/urls.py
tworaven_apps/ta2_interfaces/views_additional.py
tworaven_apps/ta3ta2-api/NOTES.md
tworavensproject/settings/base.py
tworavensproject/settings/local_settings.py

Allow UI to pull this info.  For #79:
```json
{
"success": true,
"message": "Success!",
"data": {
"version": "2017.12.20",
"TaskType": [
{
"name": "TASK_TYPE_UNDEFINED",
"label": "Task Type Undefined",
"index": 0,
"number": 0
},
{
"name": "CLASSIFICATION",
"label": "Classification",
"index": 1,
"number": 1
},
{
"name": "REGRESSION",
"label": "Regression",
"index": 2,
"number": 2
},
{
"name": "CLUSTERING",
"label": "Clustering",
"index": 3,
"number": 3
},
{
"name": "LINK_PREDICTION",
"label": "Link Prediction",
"index": 4,
"number": 4
},
{
"name": "VERTEX_NOMINATION",
"label": "Vertex Nomination",
"index": 5,
"number": 5
},
{
"name": "COMMUNITY_DETECTION",
"label": "Community Detection",
"index": 6,
"number": 6
},
{
"name": "GRAPH_CLUSTERING",
"label": "Graph Clustering",
"index": 7, …
```

API endpoint to pull problem schema info

---

tworaven_apps/configurations/utils.py
tworaven_apps/ta2_interfaces/templates/grpc/ta3ta2_api_form.html
tworaven_apps/ta2_interfaces/templates/test_requests/test_examples.html
tworaven_apps/ta2_interfaces/urls.py
tworaven_apps/ta2_interfaces/user_problem_helper.py
tworaven_apps/ta2_interfaces/views_user_problem.py

- added test endpoint to view problem doc w/o writing it

user problem discovery

---

ravens_volume/sample_01.csv
tworaven_apps/ta2_interfaces/exec_pipe_helper_test.py
tworaven_apps/ta2_interfaces/execute_pipeline_helper.py
tworaven_apps/ta2_interfaces/models.py
tworaven_apps/ta2_interfaces/req_execute_pipeline.py
tworaven_apps/ta2_interfaces/req_export_pipeline.py
tworaven_apps/ta2_interfaces/templates/test_requests/test_examples.html
tworaven_apps/ta2_interfaces/urls.py
tworaven_apps/ta2_interfaces/util_execute_pipeline.py
tworaven_apps/ta2_interfaces/view_execute_pipeline.py
tworaven_apps/utils/url_helper.py

140 execpip

---

.gitmodules
.travis.yml
requirements/base.txt
submodules/README.md
tworaven_apps/ta2_interfaces/templates/test_requests/test_examples2.html
tworavensproject/settings/base.py

for #276
- link repo by git submodule

link preprocess repo

---

tworaven_apps/ta2_interfaces/models.py
tworaven_apps/ta2_interfaces/req_stream_fit_solutions.py
tworaven_apps/ta2_interfaces/req_stream_produce_solution.py
tworaven_apps/ta2_interfaces/req_stream_score_solutions.py
tworaven_apps/ta2_interfaces/tasks.py
tworaven_apps/ta2_interfaces/templates/test_requests/test_examples2.html
tworaven_apps/ta2_interfaces/templates/test_responses/GetFitSolutionResultsRequest_ok.json
tworaven_apps/ta2_interfaces/templates/test_responses/GetProduceSolutionResultsResponse_ok.json
tworaven_apps/ta2_interfaces/templates/test_responses/GetProduceSolutionResults_ok.json
tworaven_apps/ta2_interfaces/templates/test_responses/GetScoreSolutionResultsResponse_ok.json
tworaven_apps/ta2_interfaces/testing/test_non_streaming.py
tworaven_apps/ta2_interfaces/urls.py
tworaven_apps/ta2_interfaces/views_streaming_requests.py

- updates for remaining 4 streaming api endpoints

get score solution results

---

tworaven_apps/content_pages/templates/dev_raven_links.html
tworaven_apps/ta2_interfaces/forms.py
tworaven_apps/ta2_interfaces/templates/ta2_interfaces/view_save_problem_form.html
tworaven_apps/ta2_interfaces/urls.py
tworaven_apps/ta2_interfaces/user_problem_helper.py
tworaven_apps/ta2_interfaces/util_user_problem.py
tworaven_apps/ta2_interfaces/views_user_problem.py

api endpoint to save user problem info #301

---

tworaven_apps/ta2_interfaces/forms.py
tworaven_apps/ta2_interfaces/testing/__init__.py
tworaven_apps/ta2_interfaces/testing/test_problem_writing.py
tworaven_apps/ta2_interfaces/util_user_problem.py

When writing problems, allow specific directories

319 problem directory

---

docs/ta2-notes/brown_notes.md
docs/ta2-notes/ta3_run.md
fabfile.py
requirements/base.txt
tworaven_apps/eventdata_queries/mongo_retrieve_util.py
tworaven_apps/eventdata_queries/run_test.py
tworaven_apps/ta2_interfaces/ta2_dev_util.py
tworavensproject/settings/base.py

Added fab convenience commands for #330

ta2 convenience commands

---

docs/ta2-notes/stanford_notes.md
tworaven_apps/ta2_interfaces/ta2_dev_util.py

TA2, minor change

---

tworaven_apps/ta2_interfaces/models.py

1 line to change up pass a user message to the UI

add user message to json output #348

---

assets/app/app.js
tworaven_apps/ta2_interfaces/ta2_dev_util.py

added error check with alert for problem schema #404

removed use of json/eva/latest url; 

---

assets/app/index.js
setup/nginx/nginx-kube.conf
templates/index.html
tworaven_apps/content_pages/urls.py
tworaven_apps/content_pages/views.py
tworaven_apps/utils/view_helper.py

Information for mithril to use for csrf requests, log in links, username, etc

csrf example function for #419

---

requirements/prod.txt
startup_script/event_data_start.sh
tworavensproject/wsgi_gce_event_data.py

for #90
- new wsgi file 
- run script update

for running gunicorn #90

---

.travis.yml
assets/app/app.js
requirements/base.txt
setup/nginx/nginx-kube.conf
setup/r-base/Dockerfile
startup_script/d3m_start.sh
tworaven_apps/eventdata_queries/views.py
tworavensproject/asgi.py
tworavensproject/settings/base.py
tworavensproject/settings/gce_settings.py

- mongo
- websockets (daphne server for channels)
- nginx serving static files (debug set to false)

436 daphne server

---

tworaven_apps/configurations/env_config_loader.py
tworaven_apps/configurations/models_d3m.py
tworaven_apps/configurations/static_vals.py
tworaven_apps/configurations/testing/test_2019_config.py
tworaven_apps/ta2_interfaces/ta2_dev_util.py

updates for running local TA2

---

rook/rookmkdocs.R
tworaven_apps/data_prep_utils/example_rook_params.json
tworaven_apps/data_prep_utils/new_dataset_util.py
tworaven_apps/data_prep_utils/problem_doc_maker.py
tworaven_apps/rook_services/make_datadocs_util.py
tworaven_apps/user_workspaces/utils.py

- Basic augment.  
- Some details to work out on problemDoc creation
- New workspace created and loads with augment
- post-augment Results needs some work

bypassing R mkdocs #615, create problemDoc in python

---

assets/app/index.js
fabfile.py
requirements/base.txt
templates/index.html
tworaven_apps/content_pages/templates/content_pages/dev_raven_links.html
tworaven_apps/content_pages/views.py
tworaven_apps/datamart_endpoints/datamart_info_util.py
tworaven_apps/datamart_endpoints/datamart_util.py
tworaven_apps/datamart_endpoints/models.py
tworaven_apps/datamart_endpoints/static_vals.py
tworaven_apps/datamart_endpoints/urls.py
tworaven_apps/datamart_endpoints/views.py
tworavensproject/settings/base.py

- debug: show git branch/commit in UI

read in datamart urls from environment variables

---

tworaven_apps/configurations/env_config_loader.py
tworaven_apps/configurations/management/commands/load_config.py
tworaven_apps/configurations/management/commands/load_config_by_data_dir.py
tworaven_apps/configurations/testing/test_2019_config.py
tworaven_apps/ta2_interfaces/ta2_dev_util.py

When fab running a TA2, don't delete a config if it already exists

updated to not overwrite old config #636

---

.travis.yml

Fix pycurl install for travis build

709 travis

---

R/apps/appVariableImportance.R

Categorical features and classification tasks #772 #790

---

R/databuild/mk_data_structure.r

update to 4.0.0, allow no test data

---

assets/app/index.js
assets/app/modes/dataset.js
requirements/base.txt
templates/index.html
tworaven_apps/content_pages/views.py
tworavensproject/settings/base.py

Merging prematurely to remove GIT_BRANCH_INFO

830 raven ui
